### ISSUE TITLE
on [https://howto.p2pu.org/modules/tutorial/setup/]

### ISSUE THREAD

**Issue by ebonsi** [p2pu/course-in-a-box#104]
On the p2pu tutorial session;

**Who is the course for & what will they learn?**

> Will they be building something during the course. Put this basic information on the front page of the course to give a short overview of what to expect. To update the info on the front page, go to the file:

[https://github.com/ebonsi/course-in-a-box/blob/gh-pages/index.markdown ](https://github.com/ebonsi/course-in-a-box/blob/gh-pages/index.markdown )

It is leading to:

**404: Page not found**

I tried to change the url following the previous url semantics but that did not help either.
` https://github.com/ebonsi/course-in-a-box/edit/gh-pages/index.markdown `

Could anyone that is following this development chime on this issue?
#### Is this page has been deleted?
Thanks!

**Comment by dirkcuys** [comment]
Hi @ebonsi - the correct link should be https://github.com/ebonsi/course-in-a-box/blob/gh-pages/index.md is. Given that the page has been updated I assume you've figured it out.
