### ISSUE TITLE
Update custom navbar styling to match modules

### ISSUE THREAD

**Issue by GrifP** [p2pu/course-in-a-box#132]
Nav items added directly to /includes/navigation need to be styled in same way as modules

![Screen Shot 2021-03-02 at 5 12 44 PM](https://user-images.githubusercontent.com/7155640/109722320-89058900-7b7a-11eb-8f74-4adba4207e58.png)

**Comment by dirkcuys** [comment]
The extra page links should use the same style classes as items for modules. iow "nav-item py-2". Seems like the class for modules links were changed from py-0 to py-2 but not the commented code: https://github.com/p2pu/course-in-a-box/commit/db90b099ea5f3af46f881729e7c92161e519d0a6#diff-685aab823f145ce7d8c69647c1bcef572d65655973a14032212c401924caf0cb
