### ISSUE TITLE
Docker?  Running the course-in-a-box on my (local) box

### ISSUE THREAD

**Issue by Newman5** [p2pu/course-in-a-box#146]
Hey Gang!  I know that this hasn't been updated recently.  But here is my issue.

I'd like to create a tutorial (that could become a course) using the course-in-a-box.  I figure **I'd like to get it running locally.** 

When following the instructions for Local from the readme, 
**I run this code:**
```
nsl@LAPTOP: ~/ad-ipsum/p2pu-LMS-site$ docker run -i -t --rm -u 1000:1000 -p 4000:4000 -v `pwd`:/opt/app -v `pwd`/.bundler/:/opt/bundler -e BUNDLE_PATH=~/opt/bundler -w /opt/app ruby:2.7 bash -c "bundle install && bundle exec jekyll serve --watch -H 0.0.0.0"
```
**I get this error:**
`/` is not writable.
Bundler will use `/tmp/bundler20231120-7-lprlp17' as your home directory temporarily.
There was an error while trying to write to
`/home/nsl/opt/bundler/ruby/2.7.0`. It is likely that you need to grant write
permissions for that path.

Any help would be great!

**Comment by dirkcuys** [comment]
Hi @Newman5 

I think docker is creating the `.bundler` directory with root permissions, but the image itself runs as user 1000, which then doesn't have access to the directory.

```
sudo chown 1000:1000 .bundler/
```
should sort the problem out.

**Comment by Newman5** [comment]
Hey Dirk!  Thanks for the help.  And, that chown command makes sense to me.  But it didn't work.  Here is a what I get: 
![image](https://github.com/p2pu/course-in-a-box/assets/1620405/8a092a35-f354-42d6-afdf-cad7e7a5c2a7)

Any help would be appreciated. Thanks!

**Comment by pvanheus** [comment]
This is how I run it:
```bash
docker run -i -t --rm -u 1000:1000 \
    -p 4000:4000 -v $(pwd):/opt/app \
    -v $(pwd)/.bundler/:/opt/bundler \
    -e BUNDLE_PATH=/opt/bundler \
    -w /opt/app ruby:2.7 bash \
    -c "bundle install && bundle exec jekyll serve --watch -H 0.0.0.0"
```
 This maps the bundler path to a local folder called .bundler and solves the ownership issue.

**Comment by pvanheus** [comment]
Apologies, there is an error in my example above... I think it only worked because on that machine I was user 1000. This works, without any chowns etc.

```bash

if [ ! -d .bundler ] ; then mkdir .bundler ; fi
 
docker run -i -t --rm -u $(id -u):$(id -g) \
    -p 4000:4000 -v $(pwd):/opt/app \
    -v $(pwd)/.bundler/:/opt/bundler \
    -e BUNDLE_PATH=/opt/bundler \
    -w /opt/app ruby:2.7 bash \
    -c "bundle install && bundle exec jekyll serve --watch -H 0.0.0.0"
```

@Newman5: on your command line you had `BUNDLE_PATH=~/opt/bundler` which will expand to `$HOME/opt/bundler` which in your case is `/home/nsl/opt/bundler` - thus the permission denied. You need to ensure that `BUNDLE_PATH` and the location that you map to `$(pwd)/.bundler` lines up.

**Comment by pvanheus** [comment]
Updating as Jekyll has kept evolving - you don't need to be restricted to Ruby 2.7! As of today (October 2024) Ruby 3.3 works:

```bash
#!/bin/bash

if [[ ! -d .bundler ]]; then
    mkdir .bundler
fi

docker run -i -t --rm -u $(id -u):$(id -g) \
    -p 4000:4000 -v $(pwd):/opt/app \
    -v $(pwd)/.bundler/:/opt/bundler \
    -e BUNDLE_PATH=/opt/bundler \
    -w /opt/app ruby:3.3 bash \
    -c "bundle install && bundle exec jekyll serve --watch -H 0.0.0.0"
```

You might need to delete `Gemfile.lock` if this was built with a previous version of Ruby.

**Comment by Newman5** [comment]
thanks @pvanheus!  I'm grateful and I'll loop back around to this in the coming months.  For now I'll close this issue.  Thanks for your help.  I'm confident I can figure it out - I learn so much with your help.  

Cheers!
