### ISSUE TITLE
Call to action on front page unclear

### ISSUE THREAD

**Issue by mozzadrella** [p2pu/course-in-a-box#37]
Hey @ercchy wanted to file this heard a few folks say they didn't know how to get started from the splash page.

@dirkcuys should we put "start the course" button and flick people to "start here"?

**Comment by dirkcuys** [comment]
Yes, lets give the link better text and make it look like a button. Or do you mean we should add it at the top? That can work too.

Should we rename the section "I'm in--how do I get started?"

**Comment by ercchy** [comment]
Fixed with #38 

Closing...
