### ISSUE TITLE
Connecting the forks... a drawer?

### ISSUE THREAD

**Issue by davecormier** [p2pu/course-in-a-box#53]
So... if i imagine people wanting to fork my course, before during or after the course, to control their own subcommunity of the same course... is there anyway to autogenerate a list of course-forks so that people could browse what other folks were doing with the course?

**Comment by dirkcuys** [comment]
That's a great idea @davecormier. At the moment we don't have any code doing exactly that, but it is totally possible. Adapting https://github.com/p2pu/furry-stats/ should be possible.

**Comment by dirkcuys** [comment]
Hi Dave, 6 years on your idea is still relevant :) Having seen 305 people fork the repo, the majority of the forks have been to try it out, but there has also been some successful courses. I only know of a few instances where people set it up to be forked. But for course in a box itself, it's difficult to get a sense of who used it and how successful?
